INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Akron' ,'Akron'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Air Force' ,'Air Force'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Alabama' ,'Alabama'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Albany' ,'Albany NY'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Appalachian St.' ,'Appalachian State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Arizona St.' ,'Arizona State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Arizona' ,'Arizona'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Arkansas State' ,'Arkansas State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Arkansas' ,'Arkansas'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Auburn' ,'Auburn'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Austin Peay' ,'Austin Peay'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Ball State' ,'Ball State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Baylor' ,'Baylor'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Belmont' ,'Belmont'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Boise State' ,'Boise State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Boston College' ,'Boston College'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Bowling Green' ,'Bowling Green'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Bryant' ,'Bryant'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Buffalo' ,'Buffalo'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Butler' ,'Butler'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('BYU' ,'BYU'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Cal Poly' ,'Cal Poly SLO'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('California' ,'California'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Canisius' ,'Canisius'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Cent. Michigan' ,'Central Michigan'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Charleston' ,'Coll Of Charleston'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Charlotte' ,'Charlotte U'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Cincinnati' ,'Cincinnati'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Clemson' ,'Clemson'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Cleveland State' ,'Cleveland State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Colorado State' ,'Colorado State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Creighton' ,'Creighton'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('CSU Fullerton' ,'CS Fullerton'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('CSUN' ,'CS Northridge'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Davidson' ,'Creighton'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Davidson' ,'Davidson'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Delaware' ,'Delaware'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Denver' ,'Denver'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Drake' ,'Drake'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Drexel' ,'Drexel'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Duke' ,'Duke'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('East Tenn. St.' ,'East Tenn State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Eastern Illinois' ,'Eastern Illinois'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Eastern Kentucky' ,'Eastern Kentucky'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Eastern Mich.' ,'Eastern Michigan'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Eastern Wash.' ,'Eastern Washington'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Elon' ,'Elon'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('FIU' ,'Florida Intl'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Florida Atlantic' ,'Florida Atlantic'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Florida' ,'Florida'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Fresno State' ,'Florida State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Fresno State' ,'Fresno State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Furman' ,'Furman'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Ga. Southern' ,'Georgia Southern'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Gardner-Webb' ,'Gardner Webb'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('George Mason' ,'George Mason'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Georgetown' ,'Georgetown'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Georgia State' ,'Georgia State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Georgia Tech' ,'Georgia Tech'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Georgia' ,'Georgia'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Gonzaga' ,'Gonzaga'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Hawaii' ,'Hawaii'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Hofstra' ,'Hofstra'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Houston' ,'Houston'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Idaho State' ,'Idaho State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Idaho' ,'Idaho'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Illinois State' ,'Illinois State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Illinois-Chicago' ,'Illinois Chicago'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Illinois' ,'Illinois'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Indiana State' ,'Indiana State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Indiana' ,'Indiana'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Iona' ,'Iona'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Iowa State' ,'Iowa State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Iowa' ,'Iowa'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('IPFW' ,'IPFW'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('IUPUI' ,'IUPUI'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Jacksonville St.' ,'Jacksonville State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('James Madison' ,'James Madison'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Kansas' ,'Kansas'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Kent State' ,'Kansas State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Kent State' ,'Kent State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Kentucky' ,'Kentucky'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('LIU Brooklyn' ,'Long Island'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Long Beach St.' ,'Long Beach State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Louisiana Tech' ,'Louisiana Tech'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Louisville' ,'Louisville'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Loyola (Md.)' ,'Loyola Marymount'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Loyola Marym\'t' ,'Loyola Marymount'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Manhattan' ,'Manhattan'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Marist' ,'Marist'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Marquette' ,'Marquette'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Marshall' ,'Marshall'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Maryland' ,'Maryland'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Memphis' ,'Memphis'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Mercer' ,'Mercer'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Miami (Ohio)' ,'Miami Ohio'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Mich. St.' ,'Michigan State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Michigan' ,'Michigan'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Middle Tenn.' ,'Middle Tenn St'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Minnesota' ,'Minnesota'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Mississippi St.' ,'Mississippi State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Mississippi' ,'Mississippi'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Missouri State' ,'Missouri State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Missouri' ,'Missouri'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Monmouth' ,'Monmouth'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Montana St.' ,'Montana State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Montana' ,'Montana'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Morehead State' ,'Morehead State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Murray State' ,'Murray State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Nebraska' ,'Nebraska'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Nevada' ,'Nevada'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('New Mexico' ,'New Mexico'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Niagara' ,'Niagara'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('North Carolina' ,'North Carolina'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('North Dakota St.' ,'North Dakota State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('North Dakota' ,'North Dakota'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('North Texas' ,'North Texas'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Northeastern' ,'Northeastern'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Northern Ariz.' ,'Northern Arizona'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Northern Colo.' ,'No. Colorado'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Northern Ill.' ,'Northern Illinois'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Northern Kentucky' ,'Northern Kentucky'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Northwestern' ,'Northwestern'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Notre Dame' ,'Notre Dame'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Ohio St.' ,'Ohio State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Ohio' ,'Ohio'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Oklahoma State' ,'Oklahoma State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Oklahoma' ,'Oklahoma'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Old Dominion' ,'Old Dominion'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Oral Roberts' ,'Oral Roberts'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Oregon St.' ,'Oregon State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Oregon' ,'Oregon'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Pacific' ,'Pacific'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Penn' ,'Pennsylvania'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Pepperdine' ,'Pepperdine'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Pittsburgh' ,'Pittsburgh'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Portland State' ,'Portland State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Portland' ,'Portland'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Princeton' ,'Princeton'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Providence' ,'Providence'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Purdue' ,'Purdue'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Quinnipiac' ,'Quinnipiac'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Radford' ,'Radford'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Rice' ,'Rice'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Rider' ,'Rider'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Sacramento St.' ,'Sacramento State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Sacred Heart' ,'Sacred Heart'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Samford' ,'Samford'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('San Diego State' ,'San Diego State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('San Diego' ,'San Diego'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('San Francisco' ,'San Francisco'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('San Jose State' ,'San Jose State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Santa Clara' ,'Santa Clara'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Siena' ,'Siena'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('SIUE' ,'SIU Edwardsville'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('SMU' ,'SMU'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('South Alabama' ,'South Alabama'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('South Carolina' ,'South Carolina'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('South Dakota St.' ,'South Dakota State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('South Dakota' ,'South Dakota'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('South Florida' ,'South Florida'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Southern Ill.' ,'Southern Illinois'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Southern Miss' ,'Southern Miss'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Southern Utah' ,'Southern Utah'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('St. Bonaventure' ,'St. Bonaventure'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('St. John\'s' ,'St. Johns'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('St. Peter\'s' ,'St. Peter\'s'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Stanford' ,'Stanford'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('TCU' ,'TCU'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Temple' ,'Temple'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Tennessee State' ,'Tennessee State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Tennessee Tech' ,'Tennessee Tech'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Tennessee-Martin' ,'Tennessee Martin'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Tennessee' ,'Tennessee'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Texas A&M' ,'Texas A&M'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Texas State' ,'Texas State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Texas Tech' ,'Texas Tech'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Texas-Arlington' ,'UT Arlington'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Toledo' ,'Toledo'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Towson' ,'Towson'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Troy' ,'Troy'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Tulane' ,'Tulane'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Tulsa' ,'Tulsa'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('UAB' ,'UAB'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('UC Davis' ,'UC Davis'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('UCF' ,'Central Florida'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('UCLA' ,'UCLA'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('UNLV' ,'UNLV'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('USC' ,'USC'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Utah State' ,'Utah State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Utah' ,'Utah'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('UTEP' ,'UTEP'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Vermont' ,'Vermont'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Villanova' ,'Villanova'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Virginia Tech' ,'Virginia Tech'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('VMI' ,'VMI'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Wagner' ,'Wagner'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Washington St.' ,'Washington State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Washington' ,'Washington'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Weber State' ,'Weber State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('West Virginia' ,'West Virginia'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Western Caro.' ,'Western Carolina'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Western Illinois' ,'Western Illinois'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Western Ky.' ,'Western Kentucky'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Western Mich.' ,'Western Michigan'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Wichita State' ,'Wichita State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('William & Mary' ,'William & Mary'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Wisconsin' ,'Wisconsin'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Wofford' ,'Wofford'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Wright State' ,'Wright State'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Wyoming' ,'Wyoming'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Xavier' ,'Xavier'  );
INSERT INTO ncaa_basketball_test.TEAM(SCHEDULE_NAME, SPREAD_NAME  ) VALUES ('Youngstown St.' ,'Youngstown State'  );

commit